//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t f(int64_t a1, int64_t a2, int64_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x400576 - 0x4005c7
int64_t f(int64_t a1, int64_t a2, int64_t a3) {
    int64_t v1 = 0x100000000 * (int64_t)((int32_t)a2 >> 31) | a2; // 0x4005aa
    int64_t v2 = v1 % (a1 & 0xffffffff & a3); // 0x4005bd
    int64_t result = v1 % (a3 - 5) - v2 + (int64_t)((int32_t)(0x92492493 * a1 / 0x100000000 + a1) / 4 - ((int32_t)a1 >> 31)) & 0xffffffff; // 0x4005c1
    return result;
}

// Address range: 0x4005c7 - 0x400663
int main(int argc, char ** argv) {
    // 0x4005c7
    printf("Enter x: ");
    int64_t v1; // bp-12
    scanf("%d", &v1);
    printf("Enter y: ");
    int64_t v2; // bp-16
    scanf("%d", &v2);
    printf("Enter z: ");
    int64_t v3; // bp-20
    scanf("%d", &v3);
    int64_t v4 = f(v1, v2, v3); // 0x40064b
    return printf("Answer: %d\n", v4);
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int scanf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.9.2)
// Detected functions: 2
// Decompilation date: 2019-03-15 14:13:26
