//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int64_t f(int64_t a1, int64_t a2, int64_t a3);

// ------------------------ Functions -------------------------

// Address range: 0x400576 - 0x4005b5
int64_t f(int64_t a1, int64_t a2, int64_t a3) {
    int32_t v1 = a1; // 0x400591
    return ((int64_t)(-3 * ((int32_t)(0x55555556 * a1 / 0x100000000) - (v1 >> 31)) + v1) + a3 | a2 + a1 & a2) & 0xffffffff;
}

// Address range: 0x4005b5 - 0x400651
int main(int argc, char ** argv) {
    // 0x4005b5
    printf("Enter x: ");
    int64_t v1; // bp-12
    scanf("%d", &v1);
    printf("Enter y: ");
    int64_t v2; // bp-16
    scanf("%d", &v2);
    printf("Enter z: ");
    int64_t v3; // bp-20
    scanf("%d", &v3);
    int64_t v4 = f(v1, v2, v3); // 0x400639
    return printf("Answer: %d\n", v4);
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int scanf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.9.2)
// Detected functions: 2
// Decompilation date: 2019-03-15 14:16:09
